version: 1.0.{build}

environment:
  matrix:
    - compiler: msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      MINGW_ROOT: C:\msys64\mingw64
      BOOST_ROOT: C:\msys64\mingw64
      BOOST_LIBRARYDIR: C:\msys64\mingw64\lib
      BOOST_INCLUDEDIR: C:\msys64\mingw64\include\boost
      CMAKE_GENERATOR: 'MSYS Makefiles'
    - compiler: msys2
      ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      MINGW_ROOT: C:\msys64\mingw64
      BOOST_ROOT: C:\msys64\mingw64
      BOOST_LIBRARYDIR: C:\msys64\mingw64\lib
      BOOST_INCLUDEDIR: C:\msys64\mingw64\include\boost
      CMAKE_GENERATOR: 'MSYS Makefiles'

init:
- set PATH=%MINGW_ROOT%\bin;C:\msys64\usr\bin\;%PATH%
- bash -lc "pacman --needed --noconfirm -S mingw-w64-%MSYS2_ARCH%-boost"
- bash -lc "pacman --needed --noconfirm -S mingw-w64-%MSYS2_ARCH%-dlfcn"

build_script:
- cmake -E make_directory build
- cmake -E chdir build cmake -G "%CMAKE_GENERATOR%" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_INCLUDEDIR="%BOOST_INCLUDEDIR%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DENABLE_TESTS=ON -DENABLE_PYLC3=OFF -DENABLE_COMPLX=OFF -DENABLE_AS2OBJ=OFF -DLC3_TEST_SUITE_EXTRA_LIBS=-lmingw32 ..
- cmake --build build

test_script:
- set CTEST_OUTPUT_ON_FAILURE=ON
- cmake --build build --target test

notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
