sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - os: linux
    - compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-test-dev libwxgtk3.0-dev

script:
  - mkdir build && cd build
  - cmake -DENABLE_TESTS=ON -DENABLE_COMPLX=OFF -DENABLE_LC3TEST=OFF -DENABLE_BWLCD=OFF -DENABLE_COLORLCD=OFF ..
  - make
  - sudo make install
  - sudo ldconfig
  - ctest -VV
